---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-01
  namespace: staging
  labels:
    app: cloud-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-01
  template:
    metadata:
      labels:
        app: cloud-01
    spec:
      containers:
      - name: cloud-01
        image: 910545283509.dkr.ecr.eu-central-1.amazonaws.com/backend:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-01
  namespace: staging
spec:
  selector:
    app: cloud-01
  ports:
  - protocol: TCP
    port: 8080
